#!/usr/bin/env python3
"""
Test the solver pipeline against synthetic ARC-AGI-2 problems
generated by the actual Hone generator.

Usage:
    python test_solver.py                    # Quick test (10 problems)
    python test_solver.py --count 100        # Full test
    python test_solver.py --verbose          # Show details
"""

import sys
import os
import time
import argparse

# Add Hone repo to path for generator access
HONE_PATH = os.path.join(os.path.dirname(__file__), "..", "hone", "sandbox_runner")
sys.path.insert(0, HONE_PATH)

from synthetics.arc_agi2_generator import ARC2Generator

# Add our solver to path
sys.path.insert(0, os.path.dirname(__file__))

from solver.grid_utils import grids_equal, dims
from solver.chain_detector import try_direct_transforms, try_zoom_wrapped_transforms, detect_output_chain, apply_chain
from solver.validator import validate_prediction


def generate_test_problems(count: int, seed: int = 42):
    """Generate test problems using the actual Hone generator.

    Uses the same chain length distribution as the Hone subnet:
    50% random(3,5) + 50% random(5,7) — see dataset_manager.py lines 109-113.
    """
    import random
    rng = random.Random(seed)
    gen = ARC2Generator(max_chain_length=7, max_grid_size=30, seed=seed)
    problems = []

    attempts = 0
    while len(problems) < count and attempts < count * 10:
        attempts += 1
        try:
            # Match Hone subnet distribution exactly
            if rng.random() < 0.5:
                chain_length = rng.randint(3, 5)
            else:
                chain_length = rng.randint(5, 7)

            problem_set = gen.generate_problem_set(
                num_train=3,
                num_test=1,
                chain_length=chain_length,
            )
            problems.append(problem_set)
        except Exception as e:
            continue

    return problems


def test_layer1_direct_transforms(problems, verbose=False):
    """Test Layer 1: direct transform detection only (no wrapping).

    Matches orchestrator: only try_direct_transforms in fast path.
    Wrapping strategies excluded — higher false positive rate (tested 1700 problems).
    """
    correct = 0
    attempted = 0
    total = len(problems)

    for i, prob in enumerate(problems):
        train = prob["train_examples"]
        test_input = prob["test_input"]
        test_output = prob["test_output"]
        metadata = prob.get("metadata", {})

        inputs = [ex["input"] for ex in train]
        outputs = [ex["output"] for ex in train]

        t0 = time.time()
        result = try_direct_transforms(inputs, outputs, test_input)
        dt = time.time() - t0

        if result is not None:
            attempted += 1
            if grids_equal(result, test_output):
                correct += 1
                if verbose:
                    chain = metadata.get("transformation_chain", [])
                    names = [s["name"] for s in chain]
                    print(f"  [{i+1}] CORRECT ({dt:.3f}s) chain={names}")
            else:
                if verbose:
                    chain = metadata.get("transformation_chain", [])
                    names = [s["name"] for s in chain]
                    print(f"  [{i+1}] WRONG ({dt:.3f}s) chain={names}")
        else:
            if verbose and i < 20:
                chain = metadata.get("transformation_chain", [])
                base = metadata.get("base_task", "?")
                names = [s["name"] for s in chain]
                print(f"  [{i+1}] SKIP (base={base}, chain={names})")

    return correct, attempted, total


def test_output_chain_detection(problems, verbose=False):
    """Test output chain stripping."""
    detected = 0
    correct_detection = 0
    total = len(problems)

    for i, prob in enumerate(problems):
        train = prob["train_examples"]
        metadata = prob.get("metadata", {})
        actual_chain = metadata.get("transformation_chain", [])

        inputs = [ex["input"] for ex in train]
        outputs = [ex["output"] for ex in train]

        chain = detect_output_chain(inputs, outputs)
        if chain:
            detected += 1
            # Check if detected chain names match actual (partially)
            detected_names = [s["name"] for s in chain]
            actual_names = [s["name"] for s in actual_chain]
            if detected_names and any(d in actual_names for d in detected_names):
                correct_detection += 1
            if verbose:
                print(f"  [{i+1}] Detected: {detected_names}, Actual: {actual_names}")

    return detected, correct_detection, total


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--count", type=int, default=10, help="Number of problems")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    parser.add_argument("--verbose", "-v", action="store_true")
    args = parser.parse_args()

    print(f"Generating {args.count} synthetic ARC-AGI-2 problems...")
    problems = generate_test_problems(args.count, args.seed)
    print(f"Generated {len(problems)} problems\n")

    # Test Layer 1
    print("=" * 50)
    print("LAYER 1: Direct Transform Detection")
    print("=" * 50)
    correct, attempted, total = test_layer1_direct_transforms(problems, args.verbose)
    print(f"\nResults: {correct}/{attempted} correct out of {attempted} attempted ({total} total)")
    if attempted > 0:
        print(f"  Accuracy: {correct/attempted*100:.1f}%")
    print(f"  Coverage: {attempted/total*100:.1f}% of problems")

    # Test output chain detection
    print(f"\n{'=' * 50}")
    print("OUTPUT CHAIN DETECTION")
    print("=" * 50)
    detected, correct_det, total = test_output_chain_detection(problems, args.verbose)
    print(f"\nDetected chains in {detected}/{total} problems")
    if detected > 0:
        print(f"  Correct detections: {correct_det}/{detected}")

    # Summary stats
    print(f"\n{'=' * 50}")
    print("CHAIN LENGTH DISTRIBUTION")
    print("=" * 50)
    chain_lengths = {}
    for prob in problems:
        cl = prob.get("metadata", {}).get("chain_length", 0)
        chain_lengths[cl] = chain_lengths.get(cl, 0) + 1
    for cl in sorted(chain_lengths):
        print(f"  Length {cl}: {chain_lengths[cl]} problems")

    print(f"\nBASE TASK DISTRIBUTION")
    base_tasks = {}
    for prob in problems:
        bt = prob.get("metadata", {}).get("base_task", "?")
        base_tasks[bt] = base_tasks.get(bt, 0) + 1
    for bt in sorted(base_tasks)[:20]:
        print(f"  Task {bt}: {base_tasks[bt]}")
    if len(base_tasks) > 20:
        print(f"  ... and {len(base_tasks) - 20} more")


if __name__ == "__main__":
    main()
